[project]
name = "problems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ac-library-python",
]

[tool.uv.sources]
ac-library-python = { git = "https://github.com/not522/ac-library-python.git" }
